# Generated by Django 5.1.1 on 2024-10-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogtable_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtable',
            name='image',
            field=models.ImageField(default=2, upload_to='blog/'),
            preserve_default=False,
        ),
    ]
